version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farmacia-maggia-website
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.project.name=farmacia-maggia-website"
      - "com.project.description=Farmacia Maggia Website"
